# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

[tools]
rojo = "rojo-rbx/rojo@7.7.0-rc.1"
wally = "upliftgames/wally@0.3.2"
selene = "kampfkarren/selene@0.30.0"
stylua = "JohnnyMorganz/StyLua@0.20.0"
